### ISSUE TITLE
Input/Output Conflicts

### ISSUE THREAD

**Issue by fwippy** [paradigmnomad/Producer-Framework-Mod---Artisan-Valley#1]
As per our earlier discussion on Discord, attached please find a spreadsheet tracking vanilla/mod input/output conflicts, as well as current existing/potential mod/mod conflicts pending widespread conversion of CFR mods to PFM for purpose of future-proofing.  

[input_output_conflicts.xlsx](https://github.com/paradigmnomad/Producer-Framework-Mod---Artisan-Valley/files/3998913/input_output_conflicts.xlsx)

As an additional issue, Butter and Matcha Powder as classed as Cooking rather than ArtisanGoods.

**Comment by paradigmnomad** [comment]
Fixed in 3.0.1.
